name: food_ordering_application
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist_VariableFont_wght.ttf
        - asset: assets/fonts/Quicksand_VariableFont_wght.ttf
        - asset: assets/fonts/DMSans_VariableFont_opsz_wght.ttf

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/menu_data.json
    - assets/images/background.jpg
    - assets/images/bag.png
    - assets/images/seated_person.png
    - assets/images/delivery_scooter.png

